### GET health
GET {{url}}/health
Authorization: Bearer {{token}}

### POST doc
POST {{url}}/api/docs
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Richy"
}

### GET docs
GET {{url}}/api/docs
Authorization: Bearer {{token}}
